#! /usr/bin/env ruby

## Tables of General Midi equivalences:
######################################

# Taken form http://www.goodeveca.net/midifile_rb/
# MIDIFILE_RB/EXAMPLES/GMlister
Octave_set = [
	'C',
	'C#/Db',
	'D',
	'D#/Eb',
	'E',
	'F',
	'F#/Gb',
	'G',
	'G#/Ab',
	'A',
	'A#/Bb',
	'B',
]

Program_set = [
	'Acoustic Piano',
	'Bright Piano',
	'Electric Grand',
	'Honky Tonk',
	'Electric Piano 1',
	'Electric Piano 2',
	'Harpsichord',
	'Clavinet',
	'Celesta',
	'Glockenspiel',
	'Music Box',
	'Vibraphone',
	'Marimba',
	'Xylophone',
	'Tubular Bells',
	'Dulcimer',
	'Drawbar Organ',
	'Percussive organ',
	'Rock Organ',
	'Church Organ',
	'Reed Organ',
	'Accordion',
	'Harmonica',
	'Bandoneon',
	'Acoustic Guitar',
	'Steel Guitar',
	'Jazz Guitar',
	'Clean Elec. Guitar',
	'Muted Elec. Guitar',
	'Overdrive Guitar',
	'Distortion Guitar',
	'Guitar Harmonics',
	'Acoustic Bass',
	'Fingered Elec. Bass',
	'Picked Elec. Bass',
	'Fretless Bass',
	'Slap Bass 1',
	'Slap Bass 2',
	'Synth Bass 1',
	'Synth Bass 2',
	'Violin',
	'Viola',
	'Cello',
	'Contrabass',
	'Tremolo Strings',
	'Pizzicato',
	'Harp',
	'Tympani',
	'Marcato Strings',
	'Slow Strings',
	'Synth Strings 1',
	'Synth Strings 2',
	'Choir Aahs',
	'Voice Oohs',
	'Synth Voice',
	'Orchestra Hit',
	'Trumpet',
	'Trombone',
	'Tuba',
	'Muted Trumpet',
	'French Horn',
	'Brass Section',
	'Synth Brass 1',
	'Synth Brass 2',
	'Soprano Sax',
	'Alto Sax',
	'Tenor Sax',
	'Baritone Sax',
	'Oboe',
	'English Horn',
	'Bassoon',
	'Clarinet',
	'Piccolo',
	'Flute',
	'Recorder',
	'Pan Flute',
	'Bottle Blow',
	'Shakuhachi',
	'Whistle',
	'Ocarina',
	'Squarewave Lead',
	'Sawtooth Lead',
	'Calliope Lead',
	'Chiffer Lead',
	'Charang lead',
	'Voice Lead',
	'Fifths Lead',
	'Bass & Lead',
	'New Age Pad',
	'Warm Pad',
	'Polysynth Pad',
	'Choir Pad',
	'Bowed Pad',
	'Metal Pad',
	'Halo Pad',
	'Sweep Pad',
	'FX Rain',
	'FX Soundtrack',
	'FX Crystal',
	'FX Atmosphere',
	'FX Brightness',
	'FX Goblins',
	'FX Echoes',
	'FX Sci-Fi',
	'Sitar',
	'Banjo',
	'Shamisen',
	'Koto',
	'Kalimba',
	'Bagpipes',
	'Fiddle',
	'Shannai',
	'Tinkle Bell',
	'Agogo',
	'Steel Drums',
	'Woodblock',
	'Taiko Drum',
	'Melodic Drum',
	'Synth Drum',
	'Reverse Cymbal',
	'Guitar Fret Noise',
	'Breath Noise',
	'Seashore',
	'Bird Tweet',
	'Telephone',
	'Helicopter',
	'Applause',
	'Gunshot',
	nil
]
Controller_set = {
	0=>'Bank Select (MSB)',
	1=>'Modulation (MSB)',
	2=>'Breath Control (MSB)',
	4=>'Foot Pedal (MSB)',
	5=>'Portamento Time (MSB)',
	6=>'Data Entry (MSB)',
	7=>'Main Volume (MSB)',
	8=>'Balance (MSB)',
	10=>'Pan (MSB)',
	11=>'Expression (MSB)',
	12=>'Effects-Type #1 (MSB)',
	13=>'Effects-Type #2 (MSB)',
	16=>'Gen. Purpose 1 (MSB)',
	17=>'Gen. Purpose 2 (MSB)',
	18=>'Gen. Purpose 3 (MSB)',
	19=>'Gen. Purpose 4 (MSB)',
	32=>'Bank Select (LSB)',
	64=>'Sustain Pedal',
	65=>'Portamento Pedal',
	66=>'Sustenuto Pedal',
	67=>'Soft Pedal',
	91=>'Reverb Depth',
	93=>'Chorus Depth',
	98=>'NRPN LSB',
	99=>'NRPN MSB',
	100=>'RPN LSB',
	101=>'RPN MSB',
	120=>'All Sounds Off',
	121=>'Reset All Controllers',
	123=>'All Notes Off',
	126=>'Mono Mode On',
	127=>'Poly Mode On'
}
Controller_set.default = "Undefined Controller"
Percussion_set = {
	35=>'Acoustic Bass Drum',
	36=>'Bass Drum 1',
	37=>'Side Stick',
	38=>'Acoustic Snare',
	39=>'Hand Clap',
	40=>'Electric Snare',
	41=>'Low Floor Tom',
	42=>'Closed Hi Hat',
	43=>'High Floor Tom',
	44=>'Pedal Hi-Hat',
	45=>'Low Tom',
	46=>'Open Hi-Hat',
	47=>'Low-Mid Tom',
	48=>'Hi-Mid Tom',
	49=>'Crash Cymbal 1',
	50=>'High Tom',
	51=>'Ride Cymbal 1',
	52=>'Chinese Cymbal',
	53=>'Ride Bell',
	54=>'Tambourine',
	55=>'Splash Cymbal',
	56=>'Cowbell',
	57=>'Crash Cymbal 2',
	58=>'Vibraslap',
	59=>'Ride Cymbal 2',
	60=>'Hi Bongo',
	61=>'Low Bongo',
	62=>'Mute Hi Conga',
	63=>'Open Hi Conga',
	64=>'Low Conga',
	65=>'High Timbale',
	66=>'Low Timbale',
	67=>'High Agogo',
	68=>'Low Agogo',
	69=>'Cabasa',
	70=>'Maracas',
	71=>'Short Whistle',
	72=>'Long Whistle',
	73=>'Short Guiro',
	74=>'Long Guiro',
	75=>'Claves',
	76=>'Hi Wood Block',
	77=>'Low Wood Block',
	78=>'Mute Cuica',
	79=>'Open Cuica',
	80=>'Mute Triangle',
	81=>'Open Triangle'
}

Percussion_set.default = "Undefined Percussion"
